### ISSUE TITLE
Word Template: line numbers interfering with and pushing text to next page

### ISSUE THREAD

**Issue by slukin** [naacl-org/naacl-pubs#4]
An issue with the line numbers. An empty page appeared between the frame including the paper title and the rest of the paper. 

To reproduce: from the existing NAACL 2018 word template, cut out the first 2 paragraphs of section 2 that are on page 1, then hit "delete" to move the next section up in the gap. The first page now has the title and numbers but is completely blank otherwise. The second page starts with 'abstract' and has numbers 100 - 199, but then the third page is missing numbers, and the remainder of the paper alternates between having numbers and not.

The page numbers are a big table spanning the entire page width, and the text is expected to go through it. Possible solutions could be to make the numbers on each side a single table (without spanning the page) then we wouldn't have to worry about the text box being moved around, or to somehow lock the line numbers from being edited by the authors.

**Comment by slukin** [comment]
Actually, it doesn't seem to be a page number issue (although the text boxes are selectable, which I wouldn't want)

Seems to be when you try to delete/add content from/to the **first** page, there is a hard break where the content from the second page doesn't want to move up/down. I can successfully delete/add content from/to any subsequent page and the text moves without issue.

**Comment by slukin** [comment]
Fixed. 

Recreated template from scratch. Added slight modifications to the positioning to match latex formatting more closely.

**Comment by mmitchellai** [comment]
LGTM.  Transferring over to ACL repo as well.
